title: Karel Kubíček
url: "https://karelkubicek.github.io"
baseurl: ""

markdown: kramdown
ins_logo: "./eth-logo.png"

tracking_id: #

footer: yes
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Paper posts"
   link: "posts"
 - name: "Contact"
   link: "contact"
