title: Ahmed Bouhoula's research page
author: Ahmed Bouhoula
url: "https://ahmedbouhoula.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Paper posts"
   link: "posts"

collections:
  posts:
    permalink: /post/:title:output_ext
